### ISSUE TITLE
Not thread safe, caching issues

### ISSUE THREAD

**Issue by sqrrrl** [google/google-id-token#6]
The validator itself isn't thread safe due to the use of @problem to report back status. This requires creating a new instance each time (or at least being very careful in other ways.) Creating multiple instances however partially defeats the built-in caching of certificates.

Could use a refactoring to better separate out the certificate loading/caching from the validator. It's partially there in that a list of certs can be passed in to the validator, but that leaves a lot of implementation in the hands of users of the lib.

Should be a more complete solution than what is offered.

**Comment by gguuss** [comment]
[Resolved in this PR](https://github.com/google/google-id-token/pull/10) we should add tests and close when verified.

**Comment by hxiong388** [comment]
While #10 definitely improves the thread safety by removing the `@problem` instance variable. But it's still not completely thread safe because it still uses `Hash` and `Hash#merge!` to cache the certificates.
